name: 🏗️ Build & Deploy
on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    name: 🔧 Build Artifacts
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'joblo2213')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.3.1
        with:
          java-version: 11
          distribution: adopt
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify spotbugs:spotbugs
      - uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          path: '**/spotbugsXml.xml'
      - name: Upload jars as Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: SMA-Speedwire-artifacts
          path: target/SMA-Speedwire-*.jar
      - name: Upload javadoc Artifact
        uses: actions/upload-artifact@v2
        with:
          name: SMA-Speedwire-apidocs
          path: target/apidocs/
  deploy-javadoc:
    name: 📖 Deploy Javadoc
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Cleanup old files
        run: |
          shopt -s extglob
          rm -r !(.git)
      - name: Download javadoc Artifact
        uses: actions/download-artifact@v2
        with:
          name: SMA-Speedwire-apidocs
      - name: Deploy javadoc
        run: |
          git config --global user.email "<>"
          git config --global user.name "Github Actions"
          git add .
          git diff-index --quiet HEAD || git commit --message "Update javadoc (${{ github.sha }})"
          git push
      
        
